package com.applovin.impl.sdk;

import com.adjust.sdk.Constants;
import com.google.android.gms.games.GamesStatusCodes;
import com.mopub.mobileads.CustomEventBannerAdapter;
import com.mopub.mobileads.CustomEventInterstitialAdapter;
import gs.gram.mopub.BuildConfig;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

class cb {
    public static final cd A;
    public static final cd B;
    public static final cd C;
    public static final cd D;
    public static final cd E;
    public static final cd F;
    public static final cd G;
    public static final cd H;
    public static final cd I;
    public static final cd J;
    public static final cd K;
    public static final cd L;
    public static final cd M;
    public static final cd N;
    public static final cd O;
    public static final cd P;
    public static final cd Q;
    public static final cd R;
    public static final cd S;
    public static final cd T;
    public static final cd U;
    public static final cd V;
    public static final cd W;
    public static final cd X;
    public static final cd Y;
    public static final cd Z;
    public static final cd a;
    public static final cd aA;
    public static final cd aB;
    public static final cd aC;
    public static final cd aD;
    public static final cd aE;
    public static final cd aF;
    public static final cd aG;
    public static final cd aH;
    public static final cd aI;
    public static final cd aJ;
    public static final cd aK;
    public static final cd aL;
    public static final cd aM;
    public static final cd aN;
    public static final cd aO;
    public static final cd aP;
    public static final cd aQ;
    public static final cd aR;
    public static final cd aS;
    public static final cd aT;
    public static final cd aU;
    public static final cd aV;
    public static final cd aW;
    public static final cd aX;
    public static final cd aY;
    public static final cd aZ;
    public static final cd aa;
    public static final cd ab;
    public static final cd ac;
    public static final cd ad;
    public static final cd ae;
    public static final cd af;
    public static final cd ag;
    public static final cd ah;
    public static final cd ai;
    public static final cd aj;
    public static final cd ak;
    public static final cd al;
    public static final cd am;
    public static final cd an;
    public static final cd ao;
    public static final cd ap;
    public static final cd aq;
    public static final cd ar;
    public static final cd as;
    public static final cd at;
    public static final cd au;
    public static final cd av;
    public static final cd aw;
    public static final cd ax;
    public static final cd ay;
    public static final cd az;
    public static final cd b;
    public static final cd ba;
    public static final cd bb;
    public static final cd bc;
    public static final cd bd;
    public static final cd be;
    public static final cd bf;
    public static final cd bg;
    public static final cd bh;
    public static final cd bi;
    public static final cd bj;
    public static final cd bk;
    public static final cd bl;
    public static final cd bm;
    public static final cd bn;
    public static final cd bo;
    public static final cd bp;
    public static final cd bq;
    public static final cd br;
    public static final cd bs;
    public static final cd bt;
    public static final cd bu;
    private static final List bv;
    private static final List bw;
    public static final cd c;
    public static final cd d;
    public static final cd e;
    public static final cd f;
    public static final cd g;
    public static final cd h;
    public static final cd i;
    public static final cd j;
    public static final cd k;
    public static final cd l;
    public static final cd m;
    public static final cd n;
    public static final cd o;
    public static final cd p;
    public static final cd q;
    public static final cd r;
    public static final cd s;
    public static final cd t;
    public static final cd u;
    public static final cd v;
    public static final cd w;
    public static final cd x;
    public static final cd y;
    public static final cd z;

    static {
        bv = Arrays.asList(new Class[]{Boolean.class, Float.class, Integer.class, Long.class, String.class});
        bw = new ArrayList();
        a = a("is_disabled", Boolean.valueOf(false));
        b = a("honor_publisher_settings", Boolean.valueOf(true));
        c = a("device_id", BuildConfig.FLAVOR);
        d = a("publisher_id", BuildConfig.FLAVOR);
        e = a("device_token", BuildConfig.FLAVOR);
        f = a("submit_data_retry_count", Integer.valueOf(1));
        g = a("vr_retry_count", Integer.valueOf(1));
        h = a("fetch_ad_retry_count", Integer.valueOf(1));
        i = a("is_verbose_logging", Boolean.valueOf(false));
        j = a("api_endpoint", "http://d.applovin.com/");
        k = a("adserver_endpoint", "http://a.applovin.com/");
        l = a("get_retry_delay", Long.valueOf(10000));
        m = a("hash_algorithm", Constants.SHA1);
        n = a("short_hash_size", Integer.valueOf(16));
        o = a("http_connection_timeout", Integer.valueOf(CustomEventInterstitialAdapter.DEFAULT_INTERSTITIAL_TIMEOUT_DELAY));
        p = a("fetch_ad_connection_timeout", Integer.valueOf(CustomEventInterstitialAdapter.DEFAULT_INTERSTITIAL_TIMEOUT_DELAY));
        q = a("http_socket_timeout", Integer.valueOf(WebRequest.DEFAULT_TIMEOUT));
        r = a("ad_session_minutes", Integer.valueOf(60));
        s = a("ad_request_parameters", BuildConfig.FLAVOR);
        t = a("ad_refresh_enabled", Boolean.valueOf(true));
        u = a("ad_refresh_seconds", Long.valueOf(120));
        v = a("mrec_ad_refresh_enabled", Boolean.valueOf(true));
        w = a("mrec_ad_refresh_seconds", Long.valueOf(120));
        x = a("leader_ad_refresh_enabled", Boolean.valueOf(true));
        y = a("leader_ad_refresh_seconds", Long.valueOf(120));
        z = a("plugin_version", BuildConfig.FLAVOR);
        A = a("ad_preload_enabled", Boolean.valueOf(true));
        B = a("ad_resource_caching_enabled", Boolean.valueOf(true));
        C = a("resource_cache_prefix", "https://vid.applovin.com/,https://pdn.applovin.com/,https://img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://pdn.applovin.com/,http://img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://cdnjs.cloudflare.com/");
        D = a("ad_auto_preload_sizes", "BANNER,INTER");
        E = a("ad_auto_preload_incent", Boolean.valueOf(true));
        F = a("is_tracking_enabled", Boolean.valueOf(true));
        G = a("force_back_button_enabled_always", Boolean.valueOf(false));
        H = a("countdown_color", "#C8FFFFFF");
        I = a("close_fade_in_time", Integer.valueOf(400));
        J = a("show_close_on_exit", Boolean.valueOf(true));
        K = a("text_incent_prompt_title", "Earn a Reward");
        L = a("text_incent_prompt_body", "Would you like to watch a video for a reward?");
        M = a("text_incent_prompt_yes_option", "Watch Now");
        N = a("text_incent_prompt_no_option", "No Thanks");
        O = a("text_incent_completion_title", "Video Reward");
        P = a("text_incent_completion_body_success", "You have earned a reward!");
        Q = a("text_incent_completion_body_quota_exceeded", "You have already earned the maximum reward for today.");
        R = a("text_incent_completion_body_reward_rejected", "Your reward was rejected.");
        S = a("text_incent_completion_body_network_failure", "We were unable to contact the rewards server. Please try again later.");
        T = a("text_incent_completion_close_option", "Okay");
        U = a("incent_warning_enabled", Boolean.valueOf(false));
        V = a("text_incent_warning_title", "Attention!");
        W = a("text_incent_warning_body", "You won\u2019t get your reward if the video hasn\u2019t finished.");
        X = a("text_incent_warning_close_option", "Close");
        Y = a("text_incent_warning_continue_option", "Keep Watching");
        Z = a("show_incent_prepopup", Boolean.valueOf(true));
        aa = a("show_incent_postpopup", Boolean.valueOf(true));
        ab = a("preload_capacity_banner", Integer.valueOf(1));
        ac = a("preload_capacity_mrec", Integer.valueOf(1));
        ad = a("preload_capacity_inter", Integer.valueOf(1));
        ae = a("preload_capacity_leader", Integer.valueOf(1));
        af = a("preload_capacity_incent", Integer.valueOf(2));
        ag = a("dismiss_video_on_error", Boolean.valueOf(true));
        ah = a("precache_delimiters", ")]',");
        ai = a("close_button_size_graphic", Integer.valueOf(27));
        aj = a("close_button_size_video", Integer.valueOf(30));
        ak = a("close_button_top_margin_graphic", Integer.valueOf(10));
        al = a("close_button_right_margin_graphic", Integer.valueOf(10));
        am = a("close_button_top_margin_video", Integer.valueOf(8));
        an = a("close_button_right_margin_video", Integer.valueOf(4));
        ao = a("force_back_button_enabled_poststitial", Boolean.valueOf(false));
        ap = a("force_back_button_enabled_close_button", Boolean.valueOf(false));
        aq = a("close_button_touch_area", Integer.valueOf(0));
        ar = a("is_video_skippable", Boolean.valueOf(false));
        as = a("cache_cleanup_enabled", Boolean.valueOf(false));
        at = a("cache_file_ttl_seconds", Long.valueOf(86400));
        au = a("cache_max_size_mb", Integer.valueOf(-1));
        av = a("preload_merge_init_tasks_incent", Boolean.valueOf(true));
        aw = a("preload_merge_init_tasks_inter", Boolean.valueOf(true));
        ax = a("submit_postback_timeout", Integer.valueOf(CustomEventBannerAdapter.DEFAULT_BANNER_TIMEOUT_DELAY));
        ay = a("submit_postback_retries", Integer.valueOf(10));
        az = a("widget_imp_tracking_delay", Integer.valueOf(GamesStatusCodes.STATUS_REQUEST_UPDATE_PARTIAL_SUCCESS));
        aA = a("draw_countdown_clock", Boolean.valueOf(true));
        aB = a("countdown_clock_size", Integer.valueOf(32));
        aC = a("countdown_clock_stroke_size", Integer.valueOf(4));
        aD = a("countdown_clock_text_size", Integer.valueOf(28));
        aE = a("ad_auto_preload_native", Boolean.valueOf(true));
        aF = a("widget_fail_on_slot_count_diff", Boolean.valueOf(true));
        aG = a("video_zero_length_as_computed", Boolean.valueOf(false));
        aH = a("video_countdown_clock_margin", Integer.valueOf(10));
        aI = a("video_countdown_clock_gravity", Integer.valueOf(83));
        aJ = a("preload_capacity_widget", Integer.valueOf(1));
        aK = a("widget_latch_timeout_ms", Integer.valueOf(500));
        aL = a("android_gc_on_widget_detach", Boolean.valueOf(true));
        aM = a("lhs_close_button_video", Boolean.valueOf(false));
        aN = a("lhs_close_button_graphic", Boolean.valueOf(false));
        aO = a("lhs_skip_button", Boolean.valueOf(true));
        aP = a("countdown_toggleable", Boolean.valueOf(false));
        aQ = a("native_batch_precache_count", Integer.valueOf(1));
        aR = a("mute_controls_enabled", Boolean.valueOf(false));
        aS = a("allow_user_muting", Boolean.valueOf(true));
        aT = a("mute_button_size", Integer.valueOf(32));
        aU = a("mute_button_margin", Integer.valueOf(10));
        aV = a("mute_button_gravity", Integer.valueOf(85));
        aW = a("qq", Boolean.valueOf(false));
        aX = a("hw_accelerate_webviews", Boolean.valueOf(false));
        aY = a("mute_videos", Boolean.valueOf(false));
        aZ = a("show_mute_by_default", Boolean.valueOf(false));
        ba = a("mute_with_user_settings", Boolean.valueOf(true));
        bb = a("event_tracking_endpoint", "http://rt.applovin.com/pix");
        bc = a("top_level_events", "landing,checkout,iap");
        bd = a("events_enabled", Boolean.valueOf(true));
        be = a("force_ssl", Boolean.valueOf(false));
        bf = a("postback_service_max_queue_size", Integer.valueOf(100));
        bg = a("max_postback_attempts", Integer.valueOf(3));
        bh = a("click_overlay_enabled", Boolean.valueOf(false));
        bi = a("click_overlay_color", "#66000000");
        bj = a("click_tracking_retry_count", Integer.valueOf(3));
        bk = a("click_tracking_retry_delay", Integer.valueOf(GamesStatusCodes.STATUS_REQUEST_UPDATE_PARTIAL_SUCCESS));
        bl = a("click_tracking_timeout", Integer.valueOf(CustomEventBannerAdapter.DEFAULT_BANNER_TIMEOUT_DELAY));
        bm = a("android_click_spinner_size", Integer.valueOf(50));
        bn = a("android_click_spinner_style", Integer.valueOf(16973853));
        bo = a("android_dismiss_inters_on_click", Boolean.valueOf(false));
        bp = a("android_require_external_storage_permission", Boolean.valueOf(true));
        bq = a("android_drop_nomedia", Boolean.valueOf(true));
        br = a("native_auto_cache_preload_resources", Boolean.valueOf(true));
        bs = a("video_immersive_mode_enabled", Boolean.valueOf(false));
        bt = a("sanitize_webview", Boolean.valueOf(false));
        bu = a("webview_package_name", "com.google.android.webview");
    }

    private static cd a(String str, Object obj) {
        if (obj == null) {
            throw new IllegalArgumentException("No default value specified");
        } else if (bv.contains(obj.getClass())) {
            cd cdVar = new cd(obj, null);
            bw.add(cdVar);
            return cdVar;
        } else {
            throw new IllegalArgumentException("Unsupported value type: " + obj.getClass());
        }
    }

    public static Collection a() {
        return Collections.unmodifiableList(bw);
    }

    public static int b() {
        return bw.size();
    }
}
