package com.chartboost.sdk.Model;

import com.chartboost.sdk.Libraries.g;
import com.chartboost.sdk.Libraries.g.a;
import com.chartboost.sdk.Libraries.g.k;
import com.facebook.internal.AnalyticsEvents;
import com.facebook.share.internal.ShareConstants;
import com.google.android.exoplayer.util.MimeTypes;
import com.google.android.gms.games.Games;
import com.mopub.mobileads.VastIconXmlManager;
import com.unity3d.ads.android.properties.UnityAdsConstants;

public class b {
    public static a a;
    public static a b;
    public static a c;
    public static a d;
    public static a e;
    public static a f;
    private static a g;
    private static a h;
    private static a i;
    private static a j;
    private static a k;
    private static a l;

    static {
        g = g.a(g.a(UnityAdsConstants.UNITY_ADS_FAILED_URL_URL_KEY, g.a()), g.a(UnityAdsConstants.UNITY_ADS_ZONE_ID_KEY, g.a()), g.a("local-file", g.a()), g.a("buffer", g.a(g.b())));
        k[] kVarArr = new k[3];
        kVarArr[0] = g.a(UnityAdsConstants.UNITY_ADS_FAILED_URL_URL_KEY, g.a());
        kVarArr[1] = g.a("scale", g.a(g.b()));
        kVarArr[2] = g.a(VastIconXmlManager.OFFSET, g.a(g.b(g.a("x", g.b()), g.a("y", g.b()))));
        h = g.a(kVarArr);
        i = g.a(g.a("video-landscape", g.a(g)), g.a("video-portrait", g.a(g)), g.a("ad-landscape", g.a(h)), g.a("frame-landscape", g.a(h)), g.a("close-landscape", g.a(h)), g.a("replay-landscape", g.a(h)), g.a("ad-portrait", g.a(h)), g.a("frame-portrait", g.a(h)), g.a("close-portrait", g.a(h)), g.a("replay-portrait", g.a(h)), g.a("video-click-button", g.a(h)), g.a("post-video-icon", g.a(h)), g.a("post-video-button", g.a(h)), g.a("video-confirmation-icon", g.a(h)), g.a("video-confirmation-button", g.a(h)), g.a("post-video-reward-icon", g.a(h)), g.a("blur-background", g.a(h)));
        kVarArr = new k[11];
        kVarArr[0] = g.a(NotificationCompatApi21.CATEGORY_PROGRESS, g.a(g.b(g.a("delay", g.b()), g.a("background-color", g.a()), g.a("progress-color", g.a()), g.a("border-color", g.a()), g.a("radius", g.b()))));
        kVarArr[1] = g.a("video-controls-togglable", g.a(g.c()));
        kVarArr[2] = g.a("video-controls-background", g.b(g.a(TtmlNode.ATTR_TTS_COLOR, g.a()), g.a("border-color", g.a())));
        kVarArr[3] = g.a("post-video-toaster", g.a(g.b(g.a(ShareConstants.WEB_DIALOG_PARAM_TITLE, g.a()), g.a("tagline", g.a()))));
        kVarArr[4] = g.a("pre-popup", g.a(g.b(g.a(ShareConstants.WEB_DIALOG_PARAM_TITLE, g.a()), g.a(MimeTypes.BASE_TYPE_TEXT, g.a()), g.a("confirm", g.a()), g.a("cancel", g.a()))));
        kVarArr[5] = g.a("post-popup", g.a(g.b(g.a(ShareConstants.WEB_DIALOG_PARAM_TITLE, g.a()), g.a(MimeTypes.BASE_TYPE_TEXT, g.a()), g.a("confirm", g.a()))));
        kVarArr[6] = g.a("cancel-popup", g.a(g.b(g.a(ShareConstants.WEB_DIALOG_PARAM_TITLE, g.a()), g.a(MimeTypes.BASE_TYPE_TEXT, g.a()), g.a("confirm", g.a()), g.a("cancel", g.a()))));
        kVarArr[7] = g.a("confirmation", g.a(g.b(g.a(MimeTypes.BASE_TYPE_TEXT, g.a()), g.a(TtmlNode.ATTR_TTS_COLOR, g.a()))));
        kVarArr[8] = g.a("video-progress-timer-enabled", g.a(g.c()));
        k[] kVarArr2 = new k[2];
        kVarArr2[0] = g.a(MimeTypes.BASE_TYPE_TEXT, g.a());
        kVarArr2[1] = g.a("position", g.a("inside-top", "outside-bottom"));
        kVarArr[9] = g.a("post-video-reward-toaster", g.a(g.b(kVarArr2)));
        kVarArr[10] = g.a("play-another-popup", g.a(g.b(g.a("skip-confirmation", g.c()), g.a(ShareConstants.WEB_DIALOG_PARAM_TITLE, g.a()), g.a(MimeTypes.BASE_TYPE_TEXT, g.a()), g.a("cancel", g.a()), g.a("confirm", g.a()))));
        j = g.a(g.a(kVarArr));
        kVarArr = new k[14];
        kVarArr[0] = g.a(UnityAdsConstants.UNITY_ADS_WEBVIEW_API_CLOSE, g.a(h));
        kVarArr[1] = g.a("header-center", g.a(h));
        kVarArr[2] = g.a("header-tile", g.a(h));
        kVarArr[3] = g.a("header-height", g.a(g.b()));
        kVarArr[4] = g.a("background-color", g.a(g.a()));
        kVarArr[5] = g.a("header-text", g.a(g.a()));
        kVarArr[6] = g.a("text-color", g.a(g.a()));
        kVarArr[7] = g.a("close-landscape", g.a(h));
        kVarArr[8] = g.a("header-landscape", g.a(h));
        kVarArr[9] = g.a("close-portrait", g.a(h));
        kVarArr[10] = g.a("header-portrait", g.a(h));
        kVarArr[11] = g.a("install-button", g.a(h));
        kVarArr[12] = g.a("play-button", g.a(h));
        kVarArr[13] = g.a(VastIconXmlManager.OFFSET, g.a(g.b(g.a("x", g.b()), g.a("y", g.b()))));
        a = g.a(kVarArr);
        kVarArr = new k[12];
        kVarArr[4] = g.a("assets", g.a(g.a("icon", h)));
        kVarArr[5] = g.a(MimeTypes.BASE_TYPE_TEXT, g.a(g.a()));
        kVarArr[6] = g.a(ShareConstants.WEB_DIALOG_PARAM_LINK, g.a(g.a()));
        kVarArr[7] = g.a("deep-link", g.a(g.a()));
        kVarArr[8] = g.a("itunes_id", g.a(g.a()));
        kVarArr[9] = g.a("publisher", g.a(g.a()));
        kVarArr[10] = g.a(ShareConstants.WEB_DIALOG_PARAM_DESCRIPTION, g.a(g.a()));
        kVarArr[11] = g.a("border-color", g.a(g.a()));
        k = g.b(g.a(kVarArr));
        b = g.a(g.a(Games.EXTRA_STATUS, com.chartboost.sdk.Libraries.a.a), g.a("ad_id", g.a()), g.a(ShareConstants.WEB_DIALOG_PARAM_TO, g.a()), g.a(UnityAdsConstants.UNITY_ADS_ANALYTICS_QUERYPARAM_EVENTTYPE_KEY, g.a()), g.a(AnalyticsEvents.PARAMETER_SHARE_DIALOG_SHOW_NATIVE, g.a(g.a())), g.a(ShareConstants.WEB_DIALOG_PARAM_MESSAGE, g.a()), g.a(ShareConstants.WEB_DIALOG_PARAM_LINK, g.a()), g.a("deep-link", g.a(g.a())), g.a("cgn", g.a()), g.a("creative", g.a()), g.a("assets", i), g.a("ux", j), g.a("reward", g.a(g.a(Object.class))));
        kVarArr = new k[2];
        kVarArr[0] = g.a("template", g.a());
        kVarArr[1] = g.a("elements", g.b(g.a(g.a(UnityAdsConstants.UNITY_ADS_ANALYTICS_QUERYPARAM_EVENTTYPE_KEY, g.a()), g.a(UnityAdsConstants.UNITY_ADS_ZONE_NAME_KEY, g.a()), g.a("param", g.a(g.a())), g.a("value", g.a()))));
        l = g.a(kVarArr);
        c = g.a(g.a(Games.EXTRA_STATUS, com.chartboost.sdk.Libraries.a.a), g.a(ShareConstants.WEB_DIALOG_PARAM_MESSAGE, g.a()), g.a(ShareConstants.WEB_DIALOG_PARAM_TO, g.a()), g.a("media_type", g.a(g.a())), g.a(UnityAdsConstants.UNITY_ADS_ANALYTICS_QUERYPARAM_EVENTTYPE_KEY, g.a(g.a())), g.a(ShareConstants.WEB_DIALOG_PARAM_LINK, g.a()), g.a("cgn", g.a()), g.a("prefetch_required", g.a(g.c())), g.a("show_loading", g.a(g.c())), g.a("events", g.a(g.a(new k[0]))), g.a("creative", g.a()), g.a("webview", l), g.a("ad_id", g.a()));
        d = g.a(g.a(Games.EXTRA_STATUS, com.chartboost.sdk.Libraries.a.a), g.a(ShareConstants.WEB_DIALOG_PARAM_MESSAGE, g.a()), g.a(UnityAdsConstants.UNITY_ADS_ANALYTICS_QUERYPARAM_EVENTTYPE_KEY, g.a()), g.a("assets", a), g.a("cells", k));
        kVarArr = new k[12];
        kVarArr[0] = g.a(Games.EXTRA_STATUS, com.chartboost.sdk.Libraries.a.a);
        kVarArr[1] = g.a("ad_id", g.a());
        kVarArr[2] = g.a(ShareConstants.WEB_DIALOG_PARAM_TO, g.a(g.a()));
        kVarArr[3] = g.a(UnityAdsConstants.UNITY_ADS_ANALYTICS_QUERYPARAM_EVENTTYPE_KEY, g.a(g.a()));
        kVarArr[4] = g.a(AnalyticsEvents.PARAMETER_SHARE_DIALOG_SHOW_NATIVE, g.a(g.a()));
        kVarArr[5] = g.a(ShareConstants.WEB_DIALOG_PARAM_MESSAGE, g.a(g.a()));
        kVarArr[6] = g.a(ShareConstants.WEB_DIALOG_PARAM_LINK, g.a());
        kVarArr[7] = g.a(UnityAdsConstants.UNITY_ADS_ZONE_NAME_KEY, g.a());
        kVarArr[8] = g.a("deep-link", g.a(g.a()));
        kVarArr[9] = g.a("cgn", g.a());
        kVarArr[10] = g.a("creative", g.a());
        kVarArr[11] = g.a("icons", g.a(g.a("sm", g.a()), g.a("md", g.a()), g.a("lg", g.a())));
        e = g.a(kVarArr);
        f = g.a(c, b);
    }
}
